### ISSUE TITLE
Day 1: Sept 7th Project Checklist

### ISSUE THREAD

**Issue by arielle-elak** [flllnCnstnc/GroupProject1#2]
- [x] Project title
- [x] Project description
- [x] User story
- [x] Wireframe or sketch of the design
- [x] API's to be used
- [x] Rough breakdown of tasks

**Comment by arielle-elak** [comment]
> * [ ]  Project title : Cities to Explore

> * [ ]  Project description : An interactive app that allows a user to explore a curated list of recommended cities to travel to, and things to do in them.

> * [ ]  User story : 
AS A USER
WHEN I SELECT the city from the dropdown
I AM PRESENTED with weather, restaurants, activities for that selected city, CURATED by one of our local guides.

> * [ ]  Wireframe or sketch of the design:
Basic wireframe done!

> * [ ]  API's to be used
- https://www.mediawiki.org/wiki/API:Main_page (MVP)
- https://openweathermap.org/api (MVP)
- https://rapidapi.com/obryan-software-obryan-software-default/api/compare-flight-prices/ (?)

> * [ ]  Rough breakdown of tasks:
- For each dropdown option start gathering the links to restaurants, activities for that city - what we want displayed on the page (ALL)
- Look at Pixabay for pictures of your location - try playing with some Api pulls? Test viability of Api https://pixabay.com/en/service/about/api/ (ALL)
- Start thinking about the Java structure of moving from Homepage > Four options page > Specific output page (ALL)
